### ISSUE TITLE
structure of dataset

### ISSUE THREAD

**Issue by Shelton-Zhou** [Pupy101/CLIP#1]
May I know the structure of your dataset?

**Comment by Pupy101** [comment]
> May I know the structure of your dataset?

This code is written for a dataset with image captioning. I use this https://www.kaggle.com/mrviswamitrakaushik/image-captioning-data

**Comment by Shelton-Zhou** [comment]
> > May I know the structure of your dataset?
> 
> This code is written for a dataset with image captioning. I use this https://www.kaggle.com/mrviswamitrakaushik/image-captioning-data

Great! Thanks a lot!
